### ISSUE TITLE
Ability to mock dependencies

### ISSUE THREAD

**Issue by katy-hughes-cko** [martincostello/lambda-test-server#344]
Hi! Thanks so much for this great library. I was wondering whether it was possible to mock dependencies so that we may assert on them after triggering the lambda. I've tried using the service collection in the newing up of the lambda test server:

```csharp
    // Arrange
    using var server = new LambdaTestServer(sc =>
    {
        sc.AddScoped<IEventParser, EventParser>(sp => _mockedEventParser.Object);
    });
```

and by using a service collection injected at the point of our httpclient:

```csharp
        // Act
        var serviceCollection = new ServiceCollection();
        serviceCollection.AddScoped<IEventParser, EventParser>(s => _mockedEventParser.Object);
        await Function.RunAsync(httpClient, cancellationTokenSource.Token, serviceCollection);
```
```csharp
    public static async Task RunAsync(
        HttpClient? httpClient = null,
        CancellationToken cancellationToken = default,
        ServiceCollection? serviceCollection = null)
    {
        _services = Init.Configure(serviceCollection ?? new ServiceCollection());
        Func<KinesisEvent, ILambdaContext, Task> handler = FunctionHandler;
        await LambdaBootstrapBuilder.Create(handler, new DefaultLambdaJsonSerializer())
            .UseHttpClient(httpClient)
            .Build()
            .RunAsync(cancellationToken);
    }
```

But it just ends up that the normal registration of IEventParser overrides because it's done after I suppose. Is there any other way you'd recommend doing this or is this library not designed to facilitate this kind of testing?

Thanks!

**Comment by martincostello** [comment]
Hi Katy - you _should_ be able to do this.

The only public example I have that isn't in the codebase here is [this one](https://github.com/martincostello/alexa-london-travel/blob/351283767e87356f02f869ac06b02b69031217c0/test/LondonTravel.Skill.Tests/EndToEndTests.cs#L21-L56), but that isn't overriding any existing services but just adding new ones.

In this case, it's just configuring its own internal web host (i.e. the runtime), rather than the service collection for the application under test.

In the test suites for work where I use this library, the service container for the test code is typically separate to the one the server is using. The pattern is very similar to the way the code in my [alexa function](https://github.com/martincostello/alexa-london-travel/blob/351283767e87356f02f869ac06b02b69031217c0/src/LondonTravel.Skill/AlexaFunction.cs#L94-L98) is structured.

Could it be that you need to replace the existing service registration on your container (e.g. [like this](https://stackoverflow.com/a/43591075/1064169)) _or_ that you need to configure _another_ container rather than the test server's?
